# config.yaml - ВСЕ настройки в одном месте
project:
  name: "counterfeit-detection"
  seed: 42

data:
  batch_size: 10000
  text_columns: ["title", "description"]
  metadata_columns: ["price", "brand", "category", "seller_rating"]
  target_column: "is_counterfeit"
  id_column: "item_id"

text_model:
  name: "DeepPavlov/rubert-base-cased"
  max_length: 512
  batch_size: 32

metadata_model:
  type: "xgboost"
  params:
    n_estimators: 1000
    max_depth: 7
    learning_rate: 0.01
    subsample: 0.8

fusion:
  method: "weighted_average"
  optimize_threshold: true

paths:
  train_data: "data/raw/train.parquet"
  test_data: "data/raw/test.parquet"
  models_dir: "models/"
  predictions_dir: "data/predictions/"