# Fusion Configuration
fusion:
  method: "adaptive_weighted"  # weighted, stacking, neural, adaptive_weighted

  weight_optimization:
    method: "bayesian"  # grid, random, bayesian
    n_trials: 100
    cv_folds: 5

  adaptive_weights:
    use_data_completeness: true
    use_confidence_scores: true
    min_weight: 0.1
    max_weight: 0.9

  meta_learner:
    type: "logistic_regression"  # logistic_regression, neural_network, xgboost

  calibration:
    method: "isotonic"  # isotonic, sigmoid, none

  missing_data_handling:
    text_missing_weight: 0.0
    metadata_missing_weight: 0.0
    min_required_features: 0.3