# Metadata Pipeline Configuration
metadata_pipeline:
  preprocessing:
    handle_outliers: true
    outlier_method: "iqr"  # iqr, zscore, isolation_forest
    scaling_method: "standard"  # standard, minmax, robust

  features:
    price_features:
      - "price_zscore"
      - "price_percentile_in_category"
      - "price_to_median_ratio"

    seller_features:
      - "seller_rating"
      - "seller_reviews_count"
      - "seller_trust_score"

    cross_features: true
    polynomial_features: false

  model:
    type: "xgboost"  # xgboost, lightgbm, catboost

    xgboost_params:
      n_estimators: 1000
      max_depth: 7
      learning_rate: 0.01
      subsample: 0.8
      colsample_bytree: 0.8

  missing_strategy: "smart_impute"  # drop, mean, median, smart_impute