# Text Pipeline Configuration
text_pipeline:
  preprocessing:
    lowercase: true
    remove_html: true
    remove_urls: true
    remove_emails: true
    normalize_whitespace: true
    min_text_length: 10
    max_text_length: 5000

  model:
    pretrained_model_name: "DeepPavlov/rubert-base-cased"
    # Альтернативы:
    # - "xlm-roberta-base"
    # - "cointegrated/rubert-tiny2"
    # - "ai-forever/rugpt3small_based_on_gpt2"

    max_length: 512
    batch_size: 16
    learning_rate: 2e-5
    num_epochs: 3
    warmup_steps: 500

  features:
    use_statistical: true
    use_embeddings: true
    use_brand_analysis: true

  missing_strategy: "skip"  # skip, placeholder, impute